=== rdpickard/100_days_of_code_2022/day_5/phrase_book_schema.json
{
  "$id": "https://example.com/person.schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Phrase Book",
  "type": "object",
  "properties": {
    "phrase_book_name": {
      "type": "string",
      "description": "Name of this phrasebook"
    },
    "phrase_book_description": {
      "type": "string",
      "description": "Brief description of the phrases in the list"
    },
    "maintainers": {
      "description": "Who keeps the book up to date",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "web_location": {
      "type": "string",
      "description": "URL where this phrasebook can be found"
    },
    "version": {
      "type": "string",
      "description": "Version of the phrase book as a string. "
    },
    "phrases": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "phrase": {
            "description": "The phrase that will be rendered as Morse code by the quiz",
            "type": "string"
          },
          "language": {
            "description": "The language the phrase is in.",
            "type": "string"
          },
          "hint": {
            "description": "An optional hint to the content of the phrase",
            "type": "string"
          },
          "description": {
            "description": "What the phrase is. Usuful for codes or abriviations",
            "type": "string"
          },
          "difficulty": {
            "description": "Subjective measurement of how hard the phrase may be to interpret.",
            "type": "number"
          }
        },
        "required": ["phrase"]
      }
    }
  },
  "required": [
    "phrase_book_name",
    "phrase_book_description",
    "maintainers",
    "web_location",
    "version"
  ]
}

=== rdpickard/100_days_of_code_2022/day_5/phrase_books/lingo.json
{
  "phrase_book_name": "Common radio phrases",
  "phrase_book_description": "Common expressions used in radio communications",
  "maintainers": [],
  "version": "1",
  "web_location": "",
  "phrases": [
    {
      "phrase": "Roger so far",
      "language": "",
      "hint": "",
      "description": "",
      "difficulty": 3
    },
    {
      "phrase": "Affirmative",
      "language": "",
      "hint": "",
      "description": "",
      "difficulty": 3
    },
    {
      "phrase": "Negative",
      "language": "",
      "hint": "",
      "description": "",
      "difficulty": 3
    },
    {
      "phrase": "Come in",
      "language": "",
      "hint": "",
      "description": "",
      "difficulty": 3
    },
    {
      "phrase": "Go Ahead",
      "language": "",
      "hint": "",
      "description": "",
      "difficulty": 3
    },
    {
      "phrase": "Say Again",
      "language": "",
      "hint": "",
      "description": "",
      "difficulty": 3
    },
    {
      "phrase": "Say all after",
      "language": "",
      "hint": "",
      "description": "",
      "difficulty": 3
    },
    {
      "phrase": "Say all before",
      "language": "",
      "hint": "",
      "description": "",
      "difficulty": 3
    },
    {
      "phrase": "Over",
      "language": "",
      "hint": "",
      "description": "",
      "difficulty": 3
    },
    {
      "phrase": "Out",
      "language": "",
      "hint": "",
      "description": "",
      "difficulty": 3
    },
    {
      "phrase": "Radio check",
      "language": "",
      "hint": "",
      "description": "",
      "difficulty": 3
    },
    {
      "phrase": "read you loud and clear",
      "language": "",
      "hint": "",
      "description": "",
      "difficulty": 3
    },
    {
      "phrase": "wilco",
      "language": "",
      "hint": "",
      "description": "",
      "difficulty": 3
    },
    {
      "phrase": "break break",
      "language": "",
      "hint": "",
      "description": "",
      "difficulty": 3
    },
    {
      "phrase": "Emergency emergency",
      "language": "",
      "hint": "",
      "description": "",
      "difficulty": 3
    },
    {
      "phrase": "Stand by",
      "language": "",
      "hint": "",
      "description": "",
      "difficulty": 3
    },
    {
      "phrase": "wait out",
      "language": "",
      "hint": "",
      "description": "",
      "difficulty": 3
    },
    {
      "phrase": "I spell",
      "language": "",
      "hint": "",
      "description": "",
      "difficulty": 3
    }
  ]
}
